---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}"
  labels:
    app: "{{ .Values.appName }}"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: {{ .Values.internalPort }}
    protocol: TCP
    targetPort: {{ .Values.internalPort }}
  selector:
    app: "{{ .Values.appName }}"
  sessionAffinity: None
